#### Realize as seguintes atividades usando um notebook Jupyte

In [5]:
#1º deve importar 

import math # Funções matemáticas
import numpy as np
import pandas as pd

In [12]:
#a) Explore um pouco o módulo “math”. Que funções ou constantes podem ser interessantes?

import math
math.sqrt(9) # raiz quadrada de um numero

3.0

In [11]:
#a) Explore um pouco o módulo “math”. Que funções ou constantes podem ser interessantes?

print(math.factorial(8)) #n! - Um fatorial de um número é o produto de todos os inteiros positivos menores ou iguais a esse número.
print(math.comb(60,6))   #n! / (k! * (n - k)!) - A função comb () do módulo math retorna a combinação dos valores dados, que essencialmente tem a mesma fórmula do coeficiente binomial. Um valor inteiro que representa o número de maneiras de escolher itens k de n itens sem repetição e sem ordem.
print(math.perm(60,6))   #n! / (n - k)! - Retorna o número de maneiras de escolher k itens de n itens sem repetição e com ordem. Avalia para n! / (n - k)! quando k <= n e avalia para zero quando k > n.

40320
50063860
36045979200


In [14]:
print(math.e) #O Math.E() é uma função embutida em JavaScript que é usada para obter o valor de e p , onde p é qualquer número fornecido. 
#O número e é uma constante matemática com valor aproximado igual a 2,718 

print(math.tau) #A constante matemática τ = 6.283185… Tau é uma constante de círculo igual a 2π , a razão entre a circunferência de um círculo e seu raio.

2.718281828459045
6.283185307179586


In [15]:
# podemos importar somente a função que nos interessa

from math import sqrt
sqrt(9)

3.0

In [ ]:
#Algumas funções interessantes

print(math.comb)

In [16]:
angle = [-math.pi, -math.pi / 2, 0, math.pi / 2, math.pi] 

sin = [math.sin(a) for a in angle]
cos = [math.cos(a) for a in angle]
tan = [math.tan(a) for a in angle]

pd.DataFrame({'angle': angle, 'sin': sin, 'cos': cos, 'tan': tan})

angle           sin           cos           tan
0 -3.141593 -1.224647e-16 -1.000000e+00  1.224647e-16
1 -1.570796 -1.000000e+00  6.123234e-17 -1.633124e+16
2  0.000000  0.000000e+00  1.000000e+00  0.000000e+00
3  1.570796  1.000000e+00  6.123234e-17  1.633124e+16
4  3.141593  1.224647e-16 -1.000000e+00 -1.224647e-16

In [18]:
#b) Crie um array com a seguinte característica: [[3 4 5] [5 6 4] [5 3 2]]. Calcule a dimensão dessa matriz. 

import numpy as np
A=np.array([(3,4,5),(5,6,4),(5,3,2)])
print(A)

#Tamanho da matriz
print(np.shape (A)) 

#Extraia estatísticas descritivas dessa matriz (mínimo, média, máximo e desvio padrão)
print(A.min())
print(A.max())
print(A.sum())
print(A.mean())
print(A.std())

[[3 4 5]
 [5 6 4]
 [5 3 2]]
(3, 3)
2
6
37
4.111111111111111
1.1967032904743342


In [21]:
#b) Formato mais detalhado

matrix = np.array([[3, 4, 5], [5, 6, 4], [5, 3, 2]])

print("Dimensions: ", matrix.shape)
print("Determinant: ", round(np.linalg.det(matrix), 2))
print("Inverse: ", np.linalg.inv(matrix))
print("Minimum: ", np.min(matrix))
print("Mean: ", round(np.mean(matrix), 2))
print("Maximum: ", np.max(matrix))
print("Standard deviation: ", round(np.std(matrix), 2))

Dimensions:  (3, 3)
Determinant:  -35.0
Inverse:  [[ 0.         -0.2         0.4       ]
 [-0.28571429  0.54285714 -0.37142857]
 [ 0.42857143 -0.31428571  0.05714286]]
Minimum:  2
Mean:  4.11
Maximum:  6
Standard deviation:  1.2


In [24]:
#c) Gere 2 matrizes com numeros inteiros aleatórios e promova a multiplicação entre elas. Houve algum erro? 

np.random.seed(2022)

d1 = np.random.randint(3, 12)
d2 = np.random.randint(4, 13)
d3 = np.random.randint(5, 14)

#Qual a condição para que seja possível a multiplicação de 2 matrizes? 
A = np.random.randint(1, 100, (d1, d2))
B = np.random.randint(1, 100, (d2, d3))
C = A.dot(B)

#Qual deve ser o formato da matriz resultante?
print("A dimensions: {}\n{}".format(A.shape, A))
print("\nB dimensions: {}\n{}".format(B.shape, B))
print("\nA . B dimensions: {}\n{}".format(C.shape, C))

A dimensions: (3, 5)
[[56 89 19 25 17]
 [54 42 34 28 12]
 [20 95 76 49 20]]

B dimensions: (5, 6)
[[39 73 15 94 17 91]
 [12 95 98  3 81 16]
 [24 82 88 86 38 57]
 [84 13 46 91 77 15]
 [97 14 78 53 43 54]]

A . B dimensions: (3, 6)
[[ 7457 14664 13710 10341 11539  8896]
 [ 6942 11252 10142 11310  8284  8592]
 [ 9800 17634 20112 14220 15556  9487]]


In [25]:
#d) Gere um array que seja uma sequência de números de 0 a 10, com razão de 1.2.

np.arange(0, 11, 1.2)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8])

In [26]:
#e) Gere um array que seja uma sequência de números de 100 a 10, com razão de -15.

np.arange(100, 9, -15)

array([100,  85,  70,  55,  40,  25,  10])

In [29]:
#Colocando as dezenas em ordem crescente (por linha)
megasena_ordem=np.array

In [31]:
#f) Gere uma matriz de 6x6, sendo cada linha uma sugestão aleatória de dezenas para um jogo da megasena.
megasena=np.random.randint(1,61,(6,6))
megasena

array([[39, 32, 27,  8, 35, 26],
       [46,  2, 43, 42, 37, 28],
       [33, 13,  5, 53, 56, 47],
       [41, 24, 34, 51, 11, 13],
       [26, 54, 24, 59, 25,  1],
       [55, 25, 41, 36,  5, 20]])

In [34]:
rng = np.random.default_rng()
lotery = np.asarray([sorted(rng.choice(61, size=6, replace=False)) for i in range(6)])

print("Lotery ticket dimensions: {}\n{}".format(lotery.shape, lotery))

Lotery ticket dimensions: (6, 6)
[[ 3 17 48 50 53 58]
 [11 13 24 36 37 39]
 [13 20 26 39 43 59]
 [16 17 21 23 33 48]
 [24 30 34 48 50 56]
 [17 26 42 46 48 50]]
